// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGCHgieIV-5hPvl-MnITVsAF5RsqaXBM4',
    appId: '1:203080951919:web:efc8c4923fd4d68b7dc59a',
    messagingSenderId: '203080951919',
    projectId: 'smart-time-table-management',
    authDomain: 'smart-time-table-management.firebaseapp.com',
    storageBucket: 'smart-time-table-management.firebasestorage.app',
    measurementId: 'G-H9ZF04X9R6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2fN6gOoJhBKJWYIujQ3r1GLKGAypoxdE',
    appId: '1:203080951919:ios:0bdc0e1cae0751fc7dc59a',
    messagingSenderId: '203080951919',
    projectId: 'smart-time-table-management',
    storageBucket: 'smart-time-table-management.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2fN6gOoJhBKJWYIujQ3r1GLKGAypoxdE',
    appId: '1:203080951919:ios:0bdc0e1cae0751fc7dc59a',
    messagingSenderId: '203080951919',
    projectId: 'smart-time-table-management',
    storageBucket: 'smart-time-table-management.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEoIxvrMCA1vb1XhYFifbl1Et2uE0sixc',
    appId: '1:203080951919:android:b2182fd1a5cc60117dc59a',
    messagingSenderId: '203080951919',
    projectId: 'smart-time-table-management',
    storageBucket: 'smart-time-table-management.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGCHgieIV-5hPvl-MnITVsAF5RsqaXBM4',
    appId: '1:203080951919:web:a66cc013ab9aee617dc59a',
    messagingSenderId: '203080951919',
    projectId: 'smart-time-table-management',
    authDomain: 'smart-time-table-management.firebaseapp.com',
    storageBucket: 'smart-time-table-management.firebasestorage.app',
    measurementId: 'G-BKNT7NCBHR',
  );
}
